title: Ryan Brown
email: ryancolorcafe@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My portfolio and musings on all ranges of programming topics, mainly Ruby on Rails and React.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
hosted_url: www.ryandevelops.com/
github_username: ryancolorcafe
linked_in_profile_name: ryanebrown
username: Ryan Brown
user_title: Software Engineer

markdown: kramdown
plugins:
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  blog_posts:
    output: true
    permalink: /collection/:name
  blog_tags:

pagination:
  enabled: true
  per_page: 3
  permalink: '/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  collection: 'blog_posts'
  trail:
    before: 2
    after: 2

permalink: pretty

sass:
  sass_dir: _sass
